# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/person_hobbies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/person_hobbies.proto\"^\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12 \n\x07hobbies\x18\x03 \x03(\x0b\x32\x0f.Person.Hobbies\x1a\x17\n\x07Hobbies\x12\x0c\n\x04name\x18\x01 \x01(\t\"(\n\rPersonHobbies\x12\x17\n\x06person\x18\x01 \x03(\x0b\x32\x07.Personb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSON_HOBBIES = _PERSON.nested_types_by_name['Hobbies']
_PERSONHOBBIES = DESCRIPTOR.message_types_by_name['PersonHobbies']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'Hobbies' : _reflection.GeneratedProtocolMessageType('Hobbies', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_HOBBIES,
    '__module__' : 'proto.person_hobbies_pb2'
    # @@protoc_insertion_point(class_scope:Person.Hobbies)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'proto.person_hobbies_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Hobbies)

PersonHobbies = _reflection.GeneratedProtocolMessageType('PersonHobbies', (_message.Message,), {
  'DESCRIPTOR' : _PERSONHOBBIES,
  '__module__' : 'proto.person_hobbies_pb2'
  # @@protoc_insertion_point(class_scope:PersonHobbies)
  })
_sym_db.RegisterMessage(PersonHobbies)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=30
  _PERSON._serialized_end=124
  _PERSON_HOBBIES._serialized_start=101
  _PERSON_HOBBIES._serialized_end=124
  _PERSONHOBBIES._serialized_start=126
  _PERSONHOBBIES._serialized_end=166
# @@protoc_insertion_point(module_scope)
